#!/bin/sh
### BEGIN INIT INFO
# Provides:          jackd
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: init-Script for system wide fetchmail daemon
### END INIT INFO


DAEMON=/usr/bin/jackd
USER=""
OPTIONS=""
LOG=/var/log/jackd.log
PIDFILE=/var/run/jackd.pid

## Stop the triggerhappy service
service triggerhappy stop

## Stop the dbus service. Warning: this can cause unpredictable behaviour when running a desktop environment on the RPi
#sudo service dbus stop

## Stop the console-kit-daemon service. Warning: this can cause unpredictable behaviour when running a desktop environment on the RPi
#killall console-kit-daemon

## Stop the polkitd service. Warning: this can cause unpredictable behaviour when running a desktop environment on the RPi
#killall polkitd

## Only needed when Jack2 is compiled with D-Bus support (Jack2 in the AutoStatic RPi audio repo is compiled without D-Bus support)
export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/dbus/system_bus_socket

## Remount /dev/shm to prevent memory allocation errors
mount -o remount,size=256M /dev/shm

## Kill the usespace gnome virtual filesystem daemon. Warning: this can cause unpredictable behaviour when running a desktop environment on the RPi
#killall gvfsd

## Kill the userspace D-Bus daemon. Warning: this can cause unpredictable behaviour when running a desktop environment on the RPi
#killall dbus-daemon

## Kill the userspace dbus-launch daemon. Warning: this can cause unpredictable behaviour when running a desktop environment on the RPi
#killall dbus-launch

## Uncomment if you'd like to disable the network adapter completely
#echo -n “1-1.1:1.0” | sudo tee /sys/bus/usb/drivers/smsc95xx/unbind

## Set the CPU scaling governor to performance
echo -n performance | sudo tee /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor

test -f /etc/default/jackd || exit 0
. /etc/default/jackd

JACKDHOME=/home/$USER

if [ ! "x$START_DAEMON" = "xyes" -a ! "$1" = "stop" ]; then
	echo "Edit /etc/default/jackd to start jackd"
	exit 0
fi

test -f $DAEMON || exit 0

. /lib/lsb/init-functions

case "$1" in
	start)	
	        log_begin_msg "Starting jackd audio server:" "jackd"
            echo "export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/dbus/system_bus_socket" > $JACKDHOME/.jackdinit
            echo $DAEMON $OPTIONS ' &' >> $JACKDHOME/.jackdinit
            chmod +x $JACKDHOME/.jackdinit
            su -c $JACKDHOME/.jackdinit $USER > ${LOG}
	        sleep 2
            pid=`pgrep -u ${USER} jackd` 
	        if [ pid = '' ]; then
 		        log_failure_msg "JACK daemon can't be started! Check logfile: ${LOG}"
            else
                echo $pid > $PIDFILE
 	        fi
 	        
		;;
	stop)
	        log_begin_msg "Stopping jackd audio server:" "jackd"
                pid=`cat $PIDFILE | sed -e 's/\s.*//'|head -n1` 
		if [ ! pid = '' ]; then
                        kill -9 $pid
        		log_end_msg 0
    		else
	    		log_end_msg 1
	    		exit 1
	    	fi
                rm $PIDFILE
		;;
	try-restart)
		if test -e $PIDFILE ; then
			pid=`cat $PIDFILE | sed -e 's/\s.*//'|head -n1`
			PIDDIR=/proc/$pid
			if [ -d ${PIDDIR} -a  "$(readlink -f ${PIDDIR}/exe)" = "${DAEMON}" ]; then
				$0 restart
				exit 0
			fi
		fi
		test -f /etc/rc`/sbin/runlevel | cut -d' ' -f2`.d/S*jackd* && $0 start
		;;

	*)
		log_warning_msg "Usage: /etc/init.d/jackd {start|stop|restart|force-reload|awaken|debug-run}"
		log_warning_msg "  start - starts system-wide jackd service"
		log_warning_msg "  stop  - stops system-wide jackd service"
		log_warning_msg "  restart, force-reload - starts a new system-wide jackd service"
		log_warning_msg "  awaken - tell system-wide jackd to start a poll cycle immediately"
		log_warning_msg "  debug-run [strace [strace options...]] - start a debug run of the"
		log_warning_msg "    system-wide jackd service, optionally running it under strace"
		exit 1
		;;
esac

exit 0
